### PR TITLE
Generate both real and smoke manifests before pruning

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR fixes https://github.com/rust-lang/promote-release/issues/30 by generating all the manifests before the pruning step happens, granting access to `toolstates-linux.json` to the "real" `build-manifest` invocation.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not obviously seeing the CI breakage in the diff. r=me with CI fixed unless you make some major changes and want a re-review.

**Comment by pietroalbini** [comment]
Broken CI is caused by https://github.com/rust-lang/promote-release/pull/32.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/promote-release/pull/32 landed; is there anything else blocking this PR?

**Comment by pietroalbini** [comment]
Beta CI is still broken until the beta promotion lands.

**Pull request merged**
