### PR TITLE
Create and push rust-lang/rust tags for new stable releases

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
We could consider expanding this to beta's as well (or even nightly), but for now this matches what the normal release process does well enough. It also won't currently do anything in production (we need to configure the app credentials & rustc repository; I will do that once we land this).

Unfortunately, now that we're using github API to create the tag it's harder to test that we did something reasonable, but I've done so on a fork of rustc with a non-standard name and the local one-off ephemeral gpg key, and that seemed to work well.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Given discussion about moving to GH app vs. deploy keys, we'll probably want to hold off on merging this until we adjust it to use a github app-based solution for the push authentication; shouldn't be too hard, but needs a little work.

**Comment by Mark-Simulacrum** [comment]
@pietroalbini this is now using the github app and should be ready for merge whenever you get a chance to review. My next step is probably going to be the dev-static blog post creation, fwiw.

**Review by pietroalbini — COMMENTED** [review]
The changes mostly looks good! Thanks for working on this :heart:

The code to generate the signature looks correct at a glance, I assume you tested it locally/in a fork to ensure it generates a valid signature.

**Comment by pietroalbini** [comment]
> My next step is probably going to be the dev-static blog post creation, fwiw.

Sounds good! I'd also recommend to automate tagging and signing Cargo soon, so that we can remove the requirement of loading the signing key into local machines at all during the release process.

**Comment by Mark-Simulacrum** [comment]
> The code to generate the signature looks correct at a glance, I assume you tested it locally/in a fork to ensure it generates a valid signature.

Yes, I tested against a fork -- will re-test with the latest changes, but thought I'd push first to not block CI/review. The signature seemed to be valid, though I didn't test with production signing key (mostly out of laziness to import it into the tooling), but git verify-tag did work inside the docker container to fully verify and outside to say "shrug, seems like a good signature but no public key to do much with it".

**Review by pietroalbini — APPROVED** [review]

**Comment by pietroalbini** [comment]
Great, thanks! You can merge this once you tested the latest changes.

**Comment by Mark-Simulacrum** [comment]
https://github.com/Mark-Simulacrum/rust/releases/tag/1.62.0-fake, will leave that up for now/indefinitely:

```
$ git verify-tag -v 1.62.0-fake
object a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
type commit
tag 1.62.0-fake
tagger rust-lang/promote-release <release-team@rust-lang.org> 1657372923 +0000

1.62.0 release
gpg: Signature made Sat 09 Jul 2022 09:22:03 AM EDT
gpg:                using RSA key 811D130136247726B6272812C2041E73A5FC530B
gpg: Can't check signature: No public key
$ GNUPGHOME=/persistent/gpg-home git verify-tag 1.62.0-fake
gpg: Signature made Sat Jul  9 13:22:03 2022 UTC
gpg:                using RSA key 811D130136247726B6272812C2041E73A5FC530B
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "promote-release test suite demo key <promote-release@example.com>" [ultimate]
```

**Pull request merged**
